
branches:
  only:
    - IGraphM-040

language: c

os:
  - linux
  - osx

addons:
  apt:
    packages:
    - flex
    - bison
  homebrew:
    packages:
    - flex
    - bison    

install:
  - ./get-deps.sh
  - export CPPFLAGS="-I$HOME/local/include" LDFLAGS="-L$HOME/local/lib"
  - ./bootstrap.sh
  - ./configure --with-external-glpk
  - make

script:
  - make check

after_failure:
  - find tests/testsuite.dir -name testsuite.log -exec cat \{\} \;

notifications:
  email:
    on_success: change
    on_failure: always

